const theme = {
  colors: {
    primary: "#68c184",
    secondary: "#2390ac",
    success: "#28a745",
    error: "#dc3545",
    warning: "#ffc107",
    info: "#17a2b8",
    light: "#ffffff",
    text: "#262524",
    sidebarBgColor: "#F0F8F1",
    textgray:"rgba(26, 28, 30, 0.60)",
    black: "#000",
    lightgreen: "#ebfced",
    backgray:"#e0e0e0",
    lightpink: "#FFEBEB",
    darkred: "#843838",
    lightbrown: "#FFFAE1",
    borderbrown: "#CFC079",
    lightblue: "#EDEDED",
    borderblue: "#B6B6B6" ,
    bluetext:"#2290AC",
    white:"#fff",
    lightyellow:"#f5ebbf",
    lightgreen:"#f0fff0",
    sidebarTextColor: "#1A1C1E",
    sidebarHoverBgColor: "#e0e0e0",
    sidebarHoverTextColor: "#000",
    sidebarActiveBgColor: "#d3d3d3",
    sidebarActiveTextColor: "#000",
  },
  fonts: {
    body: "'DM Sans', sans-serif",
    heading: "'Montserrat', sans-serif",
    monospace: "'Source Sans 3', monospace",
    accent: "'Nunito', sans-serif",
    display: "'Outfit', sans-serif",
  },
  breakpoints: {
    mobile: "480px",
    tablet: "768px",
    desktop: "1024px",
  },
  spacing: (factor) => `${factor * 8}px`,
};

export default theme;
